### PR TITLE
Add Doglaika Coin

### PR DESCRIPTION
**Pull request by Doglaikacoin**

### CODE REVIEW

**Comment by Doglaikacoin** [comment]
@AustinOutside could you help attend to this?

**Comment by Doglaikacoin** [comment]
Okay! Thank you…

**Comment by Doglaikacoin** [comment]
Any update yet? @AustinOutside

**Comment by AustinOutside** [comment]
Still waiting thank you

**Comment by Doglaikacoin** [comment]
@AustinOutside Should not really take too long o confirm but thanks anyways!

**Comment by Doglaikacoin** [comment]
@AustinOutside Any update yet?

**Comment by Doglaikacoin** [comment]
Hello

**Comment by AustinOutside** [comment]
Hey for the time being we are leaving tokens off the list! Will revert back in the coming weeks to see if this is something we want to change :)

**Comment by Doglaikacoin** [comment]
Okay Ser! Thank you

**Pull request closed without merging**
