### PR TITLE
Add Super Athletes Club into GameFi

### PR DESCRIPTION
**Pull request by Official-SAC**

### CODE REVIEW

**Comment by 0xneil** [comment]
@Official-SAC please add Super Athletes to the existing gaming category instead of a new gamefi category

**Review by Official-SAC — COMMENTED** [review]
move Super Athletes Club into the Gaming category.

**Comment by Official-SAC** [comment]
move Super Athletes Club to the gaming category.

**Comment by Official-SAC** [comment]
@0xneil Please check this pull request.

**Pull request closed without merging**
