### PR TITLE
Added AptStats.xyz

### PR DESCRIPTION
**Pull request by eric-allen-1112**
Added https://AptStats.xyz

### CODE REVIEW

**Review by AustinOutside — APPROVED** [review]

**Comment by moonclavedev** [comment]
Please sort the list alphabetically, thank you!

**Review by moonclavedev — CHANGES_REQUESTED** [review]
Please sort the list alphabetically, thank you!

**Comment by eric-allen-1112** [comment]
how do I change it?

**Comment by eric-allen-1112** [comment]
@AustinOutside can you please approve the change by @moonclavedev ?

**Comment by eric-allen-1112** [comment]
Updated.

**Review by AustinOutside — APPROVED** [review]

**Pull request merged**
